version: '3.8'
services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_clinic_db
    ports:
      - 3307:3306
    restart: always
    networks:
      - private
    volumes:
      - db:/var/lib/mysql
  springboot-container:
    build: .
    container_name: springboot-container 
    depends_on:
      - mysql-container
    ports:
      - 9090:9090
    restart: always
    networks:
      - public
      - private

networks:
  public:
    name: my-public-networks
    driver: bridge
  private:
    name: my-private-networks
volumes:
  db:
   driver: local    