version: '3.8'

services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_clinic_db
    ports:
      - 3306:3306
    restart: always
    networks:
      - custom_network

  springboot-container:
    build: .
    depends_on:
      - mysql-container
    ports:
      - 9090:8080
    restart: always
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
